import type { Options } from '@wdio/types';
import path from 'path';

// Path to the native build generated by `npx expo run:ios`
const APP_PATH = path.resolve(
  process.env.HOME!,
  'Library/Developer/Xcode/DerivedData/PortfolioTracker-adwfwfympgcpqrbvtfuxsqyxvlik/Build/Products/Debug-iphonesimulator/PortfolioTracker.app'
);

export const config: Options.Testrunner = {
  runner: 'local',
  port: 4723,

  specs: ['./specs/**/*.spec.ts'],

  maxInstances: 1,

  capabilities: [
    {
      platformName: 'iOS',
      'appium:automationName': 'XCUITest',
      'appium:deviceName': 'iPhone 17 Pro',
      'appium:platformVersion': '26.5',
      'appium:app': APP_PATH,
      'appium:bundleId': 'com.anonymous.portfolio-tracker',
      'appium:noReset': false,  // limpia estado entre suites
      'appium:newCommandTimeout': 240,
    },
  ],

  logLevel: 'warn',
  bail: 0,
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,

  services: [],

  framework: 'mocha',
  reporters: ['spec'],

  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
  },
};
