name: Release Packages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write # Necesario para crear tags, push al CHANGELOG y publicar Releases
  issues: write   # Necesario por si semantic-release cierra issues automáticos 
  pull-requests: write # Necesario por si semantic-release debe analizar PRs

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # IMPORTANTÍSIMO: Semantic release requiere descargar todo el historial para calcular las versiones
          persist-credentials: false # Permite que semantic-release use su token interno en lugar del default

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci # Instalación limpia basándose en el package-lock.json

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

